### PR TITLE
Switch to Pyrogram

### PR DESCRIPTION
**Pull request by rojvv**

### CODE REVIEW

**Comment by vrumger** [comment]
Is there any reason for this? It works just fine with Telethon.

**Comment by rojserbest** [comment]
@AndrewLaneX is there any reason for this? It works just like Telethon with Pyrogram.

**Comment by vrumger** [comment]
Sure, but the code is already written with Telethon, so why change it?

**Comment by rojserbest** [comment]
Who knows? Maybe for [VCPB](https://github.com/rojserbest/vcpb) in the future.

**Comment by rojvv** [comment]
This was not meant to be a pull request, I see this now. 🤔

**Pull request closed without merging**
